[package]
name = "pgpmanager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
crossterm = "0.29"
sequoia-openpgp = "2.2"
home = "0.5"
ratatui = "0.30"

[dev-dependencies]
tempfile = "3.8"
